import { describe, it, expect } from "vitest";
import {
  buildAutoGeneratedApprovalPicks,
  canManuallyActOnApprovalStep,
  optionsForApprovalStep,
  resolveParentGcCompanyId,
  type EligibleApprover,
} from "@/lib/approvalRules";
import { buildAssessmentSignatureRows } from "@/lib/approvalSignatureRows";

const mk = (partial: Partial<EligibleApprover>): EligibleApprover => ({
  out_user_id: partial.out_user_id || "u",
  out_display_name: partial.out_display_name || "이름",
  out_company_id: partial.out_company_id ?? null,
  out_company_name: partial.out_company_name || "",
  out_company_type: partial.out_company_type || "contractor",
  out_position: partial.out_position || "",
  out_role: partial.out_role || "",
});

/** 하이테크(협력사) 기안 + 상위 GC vs 진남토건(타 GC) + 발주처 */
const eligible: EligibleApprover[] = [
  mk({
    out_user_id: "author-hse",
    out_display_name: "작성자",
    out_company_id: "hitech",
    out_company_name: "하이테크",
    out_company_type: "contractor",
    out_position: "HSE_MANAGER",
    out_role: "safety_manager",
  }),
  mk({
    out_user_id: "hitech-ss",
    out_display_name: "하이테크감독",
    out_company_id: "hitech",
    out_company_name: "하이테크",
    out_company_type: "contractor",
    out_position: "SITE_SUPERVISOR",
    out_role: "site_supervisor",
  }),
  mk({
    out_user_id: "parent-hse",
    out_display_name: "상위GC안전",
    out_company_id: "parent-gc",
    out_company_name: "상위시공사",
    out_company_type: "gc",
    out_position: "HSE_MANAGER",
    out_role: "safety_manager",
  }),
  mk({
    out_user_id: "parent-sm",
    out_display_name: "상위GC소장",
    out_company_id: "parent-gc",
    out_company_name: "상위시공사",
    out_company_type: "gc",
    out_position: "SITE_MANAGER",
    out_role: "site_manager",
  }),
  mk({
    out_user_id: "jinnam-hse",
    out_display_name: "진남안전",
    out_company_id: "jinnam",
    out_company_name: "진남토건",
    out_company_type: "gc",
    out_position: "HSE_MANAGER",
    out_role: "safety_manager",
  }),
  mk({
    out_user_id: "jinnam-sm",
    out_display_name: "진남소장",
    out_company_id: "jinnam",
    out_company_name: "진남토건",
    out_company_type: "gc",
    out_position: "SITE_MANAGER",
    out_role: "site_manager",
  }),
  mk({
    out_user_id: "client-cm",
    out_display_name: "발주CM",
    out_company_id: "client",
    out_company_name: "발주처",
    out_company_type: "client",
    out_position: "OWNER_CM",
    out_role: "project_admin",
  }),
  mk({
    out_user_id: "client-sm",
    out_display_name: "발주SM",
    out_company_id: "client",
    out_company_name: "발주처",
    out_company_type: "client",
    out_position: "OWNER_SM",
    out_role: "safety_manager",
  }),
];

const companies = [
  { id: "hitech", type: "contractor", parent_company_id: "parent-gc" },
  { id: "parent-gc", type: "gc", parent_company_id: null },
  { id: "jinnam", type: "gc", parent_company_id: null },
  { id: "client", type: "client", parent_company_id: null },
];

describe("RA 결재선 생성 → 소속 인원 → 권한별 결재", () => {
  const parentGc = resolveParentGcCompanyId("hitech", companies, null);
  const ctx = {
    authorCompanyId: "hitech",
    authorCompanyType: "contractor",
    parentGcCompanyId: parentGc,
  };

  it("상위 GC는 진남토건이 아니라 parent-gc", () => {
    expect(parentGc).toBe("parent-gc");
  });

  it("시공 드롭다운: 작성자 소속(하이테크)만 — 진남/상위GC 없음", () => {
    const opts = optionsForApprovalStep(eligible, "contractor_supervisor", ctx, {
      currentUserId: "author-hse",
    });
    const companiesShown = [...new Set(opts.map((a) => a.out_company_name))];
    expect(companiesShown).toEqual(["하이테크"]);
    expect(opts.map((a) => a.out_user_id)).toEqual(["author-hse", "hitech-ss"]);
    expect(opts.some((a) => a.out_company_id === "jinnam")).toBe(false);
  });

  it("안전/소장 드롭다운: 상위 시공사만 — 진남토건·하이테크 제외", () => {
    const safety = optionsForApprovalStep(eligible, "contractor_safety_manager", ctx);
    const director = optionsForApprovalStep(eligible, "contractor_site_director", ctx);
    expect(safety.map((a) => a.out_user_id)).toEqual(["parent-hse"]);
    expect(director.map((a) => a.out_user_id)).toEqual(["parent-sm"]);
  });

  it("CM/SM 드롭다운: 발주처만", () => {
    expect(
      optionsForApprovalStep(eligible, "owner_cm", ctx).map((a) => a.out_user_id),
    ).toEqual(["client-cm"]);
    expect(
      optionsForApprovalStep(eligible, "owner_sm", ctx).map((a) => a.out_user_id),
    ).toEqual(["client-sm"]);
  });

  it("자동생성: 시공=작성자, 안전/소장=상위GC, CM/SM=발주 — 진남 없음", () => {
    const picks = buildAutoGeneratedApprovalPicks({
      eligible,
      currentUserId: "author-hse",
      ...ctx,
    });
    expect(picks.map((p) => p.approver?.out_user_id)).toEqual([
      "author-hse",
      "parent-hse",
      "parent-sm",
      "client-cm",
      "client-sm",
    ]);
    expect(picks.every((p) => p.approver?.out_company_id !== "jinnam")).toBe(true);
    expect(picks[0].approver?.out_company_name).toBe("하이테크");
  });

  it("상신 후 서명란은 결재선 5칸 — 작성/검토/승인 3칸 아님", () => {
    const picks = buildAutoGeneratedApprovalPicks({
      eligible,
      currentUserId: "author-hse",
      ...ctx,
    });
    const rows = buildAssessmentSignatureRows({
      draftSteps: picks.map((p) => ({
        label: p.label,
        position: p.position,
        user_id: p.approver?.out_user_id,
        user_name: p.approver?.out_display_name,
        company_id: p.approver?.out_company_id,
        company_name: p.approver?.out_company_name,
      })),
    });
    expect(rows).toHaveLength(5);
    expect(rows[0].company_name).toBe("하이테크");
    expect(rows.map((r) => r.step)).not.toContain("작성");
  });

  it("권한: 시공 상신칸은 수동 승인 불가 — 다음 단계 지정자만 가능", () => {
    const submitter = canManuallyActOnApprovalStep({
      actorUserId: "author-hse",
      step: { status: "진행중", approver_id: "author-hse", position: "contractor_supervisor" },
    });
    expect(submitter).toEqual({ ok: false, reason: "SUBMITTER_STEP_NO_SELF_APPROVE" });

    const otherPersonOnSafety = canManuallyActOnApprovalStep({
      actorUserId: "author-hse",
      step: { status: "진행중", approver_id: "parent-hse", position: "contractor_safety_manager" },
    });
    expect(otherPersonOnSafety).toEqual({ ok: false, reason: "NOT_AUTHORIZED" });

    const gcHse = canManuallyActOnApprovalStep({
      actorUserId: "parent-hse",
      step: { status: "진행중", approver_id: "parent-hse", position: "contractor_safety_manager" },
    });
    expect(gcHse).toEqual({ ok: true, reason: "OK" });

    const waitingSm = canManuallyActOnApprovalStep({
      actorUserId: "parent-sm",
      step: { status: "대기", approver_id: "parent-sm", position: "contractor_site_director" },
      priorIncomplete: true,
    });
    expect(waitingSm.ok).toBe(false);

    const clientSmOutOfOrder = canManuallyActOnApprovalStep({
      actorUserId: "client-sm",
      step: { status: "진행중", approver_id: "client-sm", position: "owner_sm" },
      priorIncomplete: true,
    });
    expect(clientSmOutOfOrder).toEqual({ ok: false, reason: "PRIOR_STEP_NOT_APPROVED" });
  });
});
