import { useState, useEffect, useCallback, useMemo, useImperativeHandle, useRef, forwardRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Plus, Trash2, ArrowUp, ArrowDown, RefreshCw, Users, Save } from 'lucide-react';
import {
  FIXED_APPROVAL_STEPS,
  POSITION_LABELS as SSOT_POSITION_LABELS,
  buildAutoGeneratedApprovalPicks,
  optionsForApprovalStep,
  preferAuthorCompany,
  resolveParentGcCompanyId,
  validateApprovalLinesSSOT,
  type ApprovalEntityType,
  type EligibleApprover,
} from '@/lib/approvalRules';
import { normalizeCompanyType } from '@/lib/companyTypes';
import { fetchEligibleApprovers, resolveSubmitterCompanyId } from '@/lib/eligibleApprovers';
import {
  fetchDocumentApprovalDraft,
  upsertDocumentApprovalDraft,
  type ApprovalDraftStep,
  type DocumentApprovalDraftStatus,
} from '@/lib/approvalPlatform';

interface ApprovalLine {
  id?: string;
  project_id: string;
  step_order: number;
  step_label: string;
  position: string;
  company_id: string | null;
  user_id: string | null;
  user_name: string;
  company_name: string;
}

interface ProjectMember {
  user_id: string;
  display_name: string;
  company: string;
  company_id: string | null;
  position: string;
  role: string;
}

interface Company {
  id: string;
  name: string;
  type: string;
  parent_company_id?: string | null;
}

/** 전자결재 플랫폼 — 문서별 draft 저장 대상 (프로젝트 approval_lines 와 분리) */
export type DocumentDraftTarget = {
  entityType: ApprovalEntityType;
  entityId: string;
  companyId?: string | null;
};

export type DraftStatusInfo = {
  status: DocumentApprovalDraftStatus | 'none';
  ready: boolean;
  stepCount: number;
  errors: string[];
  dirty: boolean;
};

interface Props {
  projectId: string;
  /** Used only to resolve the current user's company when RPC submitter id is needed. */
  projectMembers: ProjectMember[];
  companies: Company[];
  /** 세션 소속 회사 — 기안 회사 SSOT. 없으면 project_members 폴백. */
  submitterCompanyId?: string | null;
  /** 프로젝트 기본 시공사. 협력사 기안 시 안전·소장 범위. */
  projectGcCompanyId?: string | null;
  readOnly?: boolean;
  onLinesChanged?: (lines: ApprovalLine[]) => void;
  /**
   * 설정되면 결재선을 document_approval_drafts 에 저장한다.
   * (전자결재 플랫폼 소비자 모드 — 상신과 분리)
   */
  documentDraft?: DocumentDraftTarget;
  onDraftStatusChange?: (info: DraftStatusInfo) => void;
  /** 저장된 draft가 없을 때 쓰는 기본 단계 (순회 2단 등). */
  seedSteps?: Array<{ label: string; position: string }>;
}

export type ApprovalLineManagerHandle = {
  /** Save when dirty. Returns false if save failed or was invalid. */
  saveIfDirty: () => Promise<boolean>;
};

function linesToDraftSteps(lines: ApprovalLine[]): ApprovalDraftStep[] {
  return lines.map((l) => ({
    label: l.step_label || '',
    position: l.position || '',
    user_id: l.user_id || '',
    user_name: l.user_name || '',
    company_id: l.company_id || null,
    company_name: l.company_name || '',
  }));
}

function draftStepsToLines(projectId: string, steps: ApprovalDraftStep[]): ApprovalLine[] {
  return steps.map((s, i) => ({
    project_id: projectId,
    step_order: i,
    step_label: s.label || '',
    position: s.position || '',
    company_id: s.company_id || null,
    user_id: s.user_id || null,
    user_name: s.user_name || '',
    company_name: s.company_name || '',
  }));
}

const POSITION_LABELS: Record<string, string> = {
  ...SSOT_POSITION_LABELS,
  CEO: '대표이사',
  EXECUTIVE: '임원',
  SITE_MANAGER: '현장소장',
  HSE_MANAGER: '안전보건관리자',
  CONSTRUCTION_MGR: '공사관리자',
  FIELD_ENGINEER: '현장기사',
  FOREMAN: '작업반장',
  WORKER: '작업자',
  OWNER_PM: '발주처 PM',
  OWNER_CM: '발주처 CM',
  OWNER_SM: '발주처 SM',
  OWNER_HSE: '발주처 SM',
  SUPERVISOR: '감리',
  SITE_SUPERVISOR: '관리감독자',
};

const STEP_TEMPLATES = FIXED_APPROVAL_STEPS.map((s) => ({
  step_label: s.label,
  position: s.position,
}));

function toMemberLike(a: EligibleApprover): ProjectMember {
  return {
    user_id: a.out_user_id,
    display_name: a.out_display_name || '',
    company: a.out_company_name || '',
    company_id: a.out_company_id,
    position: a.out_position || '',
    role: a.out_role || '',
  };
}

const ApprovalLineManager = forwardRef<ApprovalLineManagerHandle, Props>(function ApprovalLineManager({
  projectId,
  projectMembers,
  companies,
  submitterCompanyId,
  projectGcCompanyId,
  readOnly,
  onLinesChanged,
  documentDraft,
  onDraftStatusChange,
  seedSteps,
}: Props, ref) {
  const { user } = useAuth();
  const { toast } = useToast();
  const [lines, setLines] = useState<ApprovalLine[]>([]);
  const [loading, setLoading] = useState(true);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [draftStatus, setDraftStatus] = useState<DocumentApprovalDraftStatus | 'none'>('none');
  const [draftErrors, setDraftErrors] = useState<string[]>([]);
  const [draftReady, setDraftReady] = useState(false);
  /** When off: 시공(상신) 단계에서 기안 회사만. 발주처/시공사 단계는 항상 해당 회사 유형 표시. */
  const [showPeerContractors, setShowPeerContractors] = useState(false);
  const [eligible, setEligible] = useState<EligibleApprover[]>([]);
  const [eligibleError, setEligibleError] = useState<string | null>(null);
  const [eligibleLoading, setEligibleLoading] = useState(true);
  const eligibleReqRef = useRef(0);
  const eligibleRef = useRef<EligibleApprover[]>([]);
  const projectMembersRef = useRef(projectMembers);
  const companiesRef = useRef(companies);
  projectMembersRef.current = projectMembers;
  companiesRef.current = companies;
  eligibleRef.current = eligible;

  const [authorCompanyId, setAuthorCompanyId] = useState<string | null>(
    () => submitterCompanyId
      || projectMembers.find((m) => m.user_id === user?.id)?.company_id
      || null,
  );
  const authorCompanyType = useMemo(() => {
    if (!authorCompanyId) return null;
    const fromEligible = eligible.find((a) => a.out_company_id === authorCompanyId)?.out_company_type;
    if (fromEligible) return normalizeCompanyType(fromEligible) || fromEligible;
    const co = companies.find((c) => c.id === authorCompanyId);
    return normalizeCompanyType(co?.type) || co?.type || null;
  }, [authorCompanyId, eligible, companies]);
  const parentGcCompanyId = useMemo(
    () => resolveParentGcCompanyId(authorCompanyId, companies, projectGcCompanyId),
    [authorCompanyId, companies, projectGcCompanyId],
  );
  const authorCompanyName = useMemo(() => {
    if (!authorCompanyId) return '';
    return companies.find((c) => c.id === authorCompanyId)?.name
      || eligible.find((a) => a.out_company_id === authorCompanyId)?.out_company_name
      || '';
  }, [authorCompanyId, companies, eligible]);

  const filterCtx = useMemo(
    () => ({ authorCompanyId, authorCompanyType, parentGcCompanyId }),
    [authorCompanyId, authorCompanyType, parentGcCompanyId],
  );

  const loadEligible = useCallback(async () => {
    const req = ++eligibleReqRef.current;
    setEligibleError(null);
    const members = projectMembersRef.current;
    const fromProp = members.find((m) => m.user_id === user?.id)?.company_id || null;
    const resolved = await resolveSubmitterCompanyId(
      projectId,
      user?.id || null,
      submitterCompanyId || fromProp || null,
    );
    if (req !== eligibleReqRef.current) return;
    const companyId = resolved || submitterCompanyId || fromProp || null;
    setAuthorCompanyId(companyId);

    const { data, error } = await fetchEligibleApprovers(projectId, companyId);
    if (req !== eligibleReqRef.current) return;
    if (error) {
      console.warn('[ApprovalLineManager] get_eligible_approvers failed:', error);
      setEligibleError(error);
      if (eligibleRef.current.length === 0) {
        const cos = companiesRef.current;
        setEligible(
          members
            .filter((m) => m.user_id && !String(m.user_id).startsWith('mgr:'))
            .map((m) => ({
              out_user_id: m.user_id,
              out_display_name: m.display_name,
              out_company_id: m.company_id,
              out_company_name: m.company,
              out_company_type: cos.find((c) => c.id === m.company_id)?.type || '',
              out_position: m.position,
              out_role: m.role,
            })),
        );
      }
      setEligibleLoading(false);
      return;
    }
    setEligible(data);
    setEligibleLoading(false);
  }, [projectId, user?.id, submitterCompanyId]);

  const fetchLines = useCallback(async () => {
    setLoading(true);
    if (documentDraft) {
      const draft = await fetchDocumentApprovalDraft(documentDraft.entityType, documentDraft.entityId);
      if (draft && draft.steps.length > 0) {
        setLines(draftStepsToLines(projectId, draft.steps));
        setDraftStatus(draft.status);
        setDraftReady(draft.status === 'ready');
        setDraftErrors(draft.validation_errors || []);
      } else {
        // 시드: 프로젝트 기본 결재선 (있을 때만). ready 로 올리지 않음 — [저장] 필수.
        const { data } = await supabase
          .from('approval_lines')
          .select('*')
          .eq('project_id', projectId)
          .order('step_order');
        if (seedSteps && seedSteps.length > 0) {
          setLines(seedSteps.map((s, i) => ({
            project_id: projectId,
            step_order: i,
            step_label: s.label,
            position: s.position,
            company_id: documentDraft.companyId || null,
            user_id: null,
            user_name: '',
            company_name: '',
          })));
        } else if (data && data.length > 0) {
          setLines(data as ApprovalLine[]);
        } else {
          setLines([]);
        }
        setDraftStatus('none');
        setDraftReady(false);
        setDraftErrors([]);
      }
      setDirty(false);
      setLoading(false);
      return;
    }

    const { data } = await supabase
      .from('approval_lines')
      .select('*')
      .eq('project_id', projectId)
      .order('step_order');
    if (data && data.length > 0) {
      setLines(data as ApprovalLine[]);
    } else {
      setLines([]);
    }
    setLoading(false);
  }, [projectId, documentDraft?.entityType, documentDraft?.entityId, documentDraft?.companyId, seedSteps]);

  useEffect(() => {
    void fetchLines();
  }, [fetchLines]);

  useEffect(() => {
    void loadEligible();
  }, [loadEligible]);

  useEffect(() => {
    onLinesChanged?.(lines);
  }, [lines, onLinesChanged]);

  useEffect(() => {
    onDraftStatusChange?.({
      status: draftStatus,
      ready: draftReady && !dirty,
      stepCount: lines.length,
      errors: draftErrors,
      dirty,
    });
  }, [draftStatus, draftReady, dirty, lines.length, draftErrors, onDraftStatusChange]);

  const optionsForStep = useCallback(
    (position: string): EligibleApprover[] => {
      if (!position) return [];
      let list = optionsForApprovalStep(eligible, position, filterCtx, {
        currentUserId: user?.id || null,
      });
      // Optional: peer 협력사도 시공(상신) 단계에 표시
      if (
        showPeerContractors &&
        (position === 'contractor_supervisor' || position === 'site_supervisor' || position === 'supervisor')
      ) {
        const peers = eligible.filter((a) => {
          const t = normalizeCompanyType(a.out_company_type);
          const pos = (a.out_position || '').toUpperCase();
          const role = (a.out_role || '').toLowerCase();
          return (
            (t === 'contractor' || t === 'vendor') &&
            a.out_company_id !== authorCompanyId &&
            (pos === 'SITE_SUPERVISOR' || role === 'site_supervisor')
          );
        });
        const seen = new Set(list.map((a) => a.out_user_id));
        for (const p of peers) {
          if (!seen.has(p.out_user_id)) list = [...list, p];
        }
      }
      return preferAuthorCompany(list, authorCompanyId);
    },
    [eligible, filterCtx, showPeerContractors, authorCompanyId, user?.id],
  );

  const autoGenerate = () => {
    if (!user) return;
    const picks = buildAutoGeneratedApprovalPicks({
      eligible,
      currentUserId: user.id,
      authorCompanyId,
      authorCompanyType,
      parentGcCompanyId,
    });
    const newLines: ApprovalLine[] = picks.map((p, i) => ({
      project_id: projectId,
      step_order: i,
      step_label: p.label,
      position: p.position,
      company_id: p.approver?.out_company_id || null,
      user_id: p.approver?.out_user_id || null,
      user_name: p.approver?.out_display_name || '',
      company_name: p.approver?.out_company_name || '',
    }));

    setLines(newLines);
    setDirty(true);
    const filled = newLines.filter((l) => l.user_id).length;
    const hasClient = eligible.some(
      (a) => normalizeCompanyType(a.out_company_type) === 'client',
    );
    const hint =
      filled < 5
        ? hasClient
          ? '미지정 단계는 수동으로 결재자를 선택하세요. [저장]을 눌러야 반영됩니다.'
          : '발주처(client) 멤버가 프로젝트에 없거나 직책이 비어 있습니다. 멤버·직책을 확인하세요.'
        : '[저장]을 눌러야 상신 점검에 반영됩니다.';
    toast({
      title: `결재라인 5단계 생성 (지정 ${filled}/5)`,
      description: authorCompanyName ? `기안 회사: ${authorCompanyName}. ${hint}` : hint,
    });
  };

  const handleSave = async (): Promise<boolean> => {
    if (lines.length === 0) {
      toast({ title: '저장할 결재라인이 없습니다.', variant: 'destructive' });
      return false;
    }
    const incomplete = lines.filter((l) => !l.position || !l.step_label || !l.user_id);
    if (incomplete.length > 0) {
      toast({
        title: '구분·결재자가 비어 있는 단계가 있습니다.',
        description: '단계 추가 후 구분과 결재자를 모두 지정하거나, 빈 단계를 삭제한 뒤 저장하세요.',
        variant: 'destructive',
      });
      return false;
    }
    const ssot = validateApprovalLinesSSOT(lines);
    if (!ssot.ok) {
      toast({
        title: '구형/잘못된 단계 키가 있습니다.',
        description: `자동 생성으로 다시 만들거나 구분을 다시 선택하세요: ${Array.from(new Set(ssot.invalid)).join(', ')}`,
        variant: 'destructive',
      });
      return false;
    }
    const invalidLines = lines.filter(
      (l) => l.user_id && !eligible.some((a) => a.out_user_id === l.user_id),
    );
    if (invalidLines.length > 0) {
      toast({
        title: '결재자가 선택 가능한 후보에 없습니다.',
        description: '발주처/시공사 멤버가 프로젝트에 등록돼 있는지 확인하세요.',
        variant: 'destructive',
      });
      return false;
    }

    // ---- 전자결재 플랫폼: 문서 draft 저장 (상신과 분리) ----
    if (documentDraft) {
      setSaving(true);
      const companyId =
        documentDraft.companyId
        || authorCompanyId
        || projectMembers.find((m) => m.user_id === user?.id)?.company_id
        || null;
      const { data, error } = await upsertDocumentApprovalDraft({
        entityType: documentDraft.entityType,
        entityId: documentDraft.entityId,
        projectId,
        companyId,
        steps: linesToDraftSteps(lines),
      });
      setSaving(false);
      if (error || !data) {
        toast({
          title: '결재선 저장 실패',
          description: error || 'document_approval_drafts RPC를 확인하세요. (Dashboard SQL 적용 여부)',
          variant: 'destructive',
        });
        return false;
      }
      setDraftStatus(data.status);
      setDraftReady(!!data.ready);
      setDraftErrors(data.errors || []);
      setDirty(false);
      if (data.ready) {
        toast({
          title: '결재선 저장 완료 — 상신 가능',
          description: `${data.steps.length}단계가 이 문서에 저장되었습니다. [결재 상신]은 별도 버튼입니다.`,
        });
        return true;
      }
      toast({
        title: '결재선 임시 저장 (상신 불가)',
        description: (data.errors || []).join(' · ') || '요건을 보완한 뒤 다시 저장하세요.',
        variant: 'destructive',
      });
      return false;
    }

    const inserts = lines.map((l, i) => ({
      project_id: projectId,
      step_order: i,
      step_label: l.step_label,
      position: l.position,
      company_id: l.company_id || null,
      user_id: l.user_id || null,
      user_name: l.user_name || '',
      company_name: l.company_name || '',
    }));

    // Snapshot for rollback if delete succeeds but insert fails
    const { data: previous, error: prevErr } = await supabase
      .from('approval_lines')
      .select('project_id, step_order, step_label, position, company_id, user_id, user_name, company_name')
      .eq('project_id', projectId)
      .order('step_order');
    if (prevErr) {
      toast({ title: '결재라인 저장 실패', description: prevErr.message, variant: 'destructive' });
      return false;
    }

    const { error: delErr } = await supabase.from('approval_lines').delete().eq('project_id', projectId);
    if (delErr) {
      toast({
        title: '결재라인 저장 권한이 없습니다.',
        description: delErr.message || '관리감독자/안전관리자/관리자만 저장할 수 있습니다.',
        variant: 'destructive',
      });
      return false;
    }

    const { error: insErr } = await supabase.from('approval_lines').insert(inserts);
    if (insErr) {
      if (previous && previous.length > 0) {
        await supabase.from('approval_lines').insert(previous);
      }
      toast({
        title: '결재라인 저장 실패',
        description: insErr.message || '권한 또는 데이터 오류로 저장되지 않았습니다. 이전 결재선을 복구했습니다.',
        variant: 'destructive',
      });
      await fetchLines();
      return false;
    }

    setDirty(false);
    toast({ title: '결재라인 저장 완료' });
    await fetchLines();
    return true;
  };

  useImperativeHandle(ref, () => ({
    saveIfDirty: async () => {
      if (!dirty) return true;
      return handleSave();
    },
  }), [dirty, handleSave]);

  const addStep = () => {
    setLines((prev) => [
      ...prev,
      {
        project_id: projectId,
        step_order: prev.length,
        step_label: '',
        position: '',
        company_id: null,
        user_id: null,
        user_name: '',
        company_name: '',
      },
    ]);
    setDirty(true);
  };

  const removeStep = (index: number) => {
    setLines((prev) => prev.filter((_, i) => i !== index));
    setDirty(true);
  };

  const moveStep = (index: number, dir: -1 | 1) => {
    const newIndex = index + dir;
    if (newIndex < 0 || newIndex >= lines.length) return;
    const updated = [...lines];
    [updated[index], updated[newIndex]] = [updated[newIndex], updated[index]];
    setLines(updated);
    setDirty(true);
  };

  const updateLine = (index: number, field: string, value: any) => {
    setLines((prev) => {
      const updated = [...prev];
      updated[index] = { ...updated[index], [field]: value };

      if (field === 'step_label' && value) {
        const template = STEP_TEMPLATES.find((t) => t.step_label === value);
        if (template) {
          updated[index].position = template.position;
          // Clear approver when step type changes — old person may be wrong company
          updated[index].user_id = null;
          updated[index].user_name = '';
          updated[index].company_id = null;
          updated[index].company_name = '';
        }
      }

      if (field === 'user_id' && value) {
        const a = eligible.find((m) => m.out_user_id === value);
        if (a) {
          updated[index].user_name = a.out_display_name;
          updated[index].company_name = a.out_company_name || '';
          updated[index].company_id = a.out_company_id || null;
        } else {
          const member = toMemberLike({
            out_user_id: value,
            out_display_name: '',
            out_company_id: null,
            out_company_name: '',
            out_company_type: '',
            out_position: '',
            out_role: '',
          });
          const m = projectMembers.find((x) => x.user_id === value) || member;
          updated[index].user_name = m.display_name;
          updated[index].company_name = m.company || '';
          updated[index].company_id = m.company_id || null;
        }
      }
      return updated;
    });
    setDirty(true);
  };

  if (loading) return <div className="text-xs text-muted-foreground p-4">결재라인 로딩 중...</div>;

  const clientCount = eligible.filter((a) => normalizeCompanyType(a.out_company_type) === 'client').length;
  const gcCount = eligible.filter((a) => normalizeCompanyType(a.out_company_type) === 'gc').length;

  const statusBadge = (() => {
    if (!documentDraft) return null;
    if (dirty) return <Badge variant="secondary" className="text-[10px]">수정됨 · 저장 필요</Badge>;
    if (draftStatus === 'ready' && draftReady) {
      return <Badge className="text-[10px] bg-emerald-600 hover:bg-emerald-600">상신 가능</Badge>;
    }
    if (draftStatus === 'submitted') {
      return <Badge variant="outline" className="text-[10px]">상신됨</Badge>;
    }
    if (draftStatus === 'draft') {
      return <Badge variant="destructive" className="text-[10px]">미완 · 보완 후 저장</Badge>;
    }
    return <Badge variant="secondary" className="text-[10px]">미저장</Badge>;
  })();

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <CardTitle className="text-sm flex items-center gap-1.5">
            <Users className="h-4 w-4" />
            {documentDraft ? '결재선 설정 (이 문서)' : '결재라인 설정'}
            {statusBadge}
          </CardTitle>
          {!readOnly && (
            <div className="flex gap-1.5 items-center flex-wrap">
              <label className="flex items-center gap-1 text-[11px] text-muted-foreground cursor-pointer select-none mr-1">
                <input
                  type="checkbox"
                  className="h-3 w-3"
                  checked={showPeerContractors}
                  onChange={(e) => setShowPeerContractors(e.target.checked)}
                />
                타 협력사(동급) 포함
              </label>
              {!seedSteps?.length && (
                <Button size="sm" variant="outline" className="gap-1 text-xs h-7" onClick={autoGenerate}>
                  <RefreshCw className="h-3 w-3" /> 자동 생성
                </Button>
              )}
              <Button size="sm" variant="outline" className="gap-1 text-xs h-7" onClick={addStep}>
                <Plus className="h-3 w-3" /> 단계 추가
              </Button>
              {(dirty || documentDraft) && (
                <Button
                  size="sm"
                  className="gap-1 text-xs h-7"
                  onClick={handleSave}
                  disabled={saving || (!dirty && documentDraft && draftReady)}
                >
                  <Save className="h-3 w-3" />
                  {saving ? '저장 중…' : documentDraft ? '결재선 저장' : '저장'}
                </Button>
              )}
            </div>
          )}
        </div>
        <p className="text-[10px] text-muted-foreground mt-1">
          {documentDraft
            ? '이 문서의 결재선만 저장합니다. 저장과 상신은 별개입니다. 미저장 상태로 상신할 수 없습니다.'
            : '프로젝트 기본 결재선입니다.'}
          {' '}결재 후보(소속+상위): {eligibleLoading && eligible.length === 0
            ? '불러오는 중…'
            : `발주처 ${clientCount}명 · 시공사 ${gcCount}명 · 전체 ${eligible.length}명`}
          {eligibleError ? ` · RPC 실패(폴백): ${eligibleError}` : ''}
        </p>
        {documentDraft && draftErrors.length > 0 && !dirty && (
          <p className="text-[10px] text-destructive mt-1">{draftErrors.join(' · ')}</p>
        )}
      </CardHeader>
      <CardContent>
        {lines.length === 0 ? (
          <div className="text-center py-6 text-sm text-muted-foreground">
            결재라인이 설정되지 않았습니다.
            {!readOnly && (
              <p className="mt-1 text-xs">[자동 생성] 버튼으로 프로젝트 멤버 기반 결재라인을 만들 수 있습니다.</p>
            )}
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs border-collapse">
              <thead>
                <tr className="bg-muted/50">
                  <th className="border px-2 py-1.5 text-left font-medium w-10">순서</th>
                  <th className="border px-2 py-1.5 text-left font-medium">구분</th>
                  <th className="border px-2 py-1.5 text-left font-medium">직책</th>
                  <th className="border px-2 py-1.5 text-left font-medium">결재자</th>
                  <th className="border px-2 py-1.5 text-left font-medium">소속</th>
                  {!readOnly && <th className="border px-2 py-1.5 text-center font-medium w-24">작업</th>}
                </tr>
              </thead>
              <tbody>
                {lines
                  .filter((l) => !(readOnly && l.position === 'cooperator' && !l.user_id))
                  .map((line, i) => {
                    const options = optionsForStep(line.position);
                    const selected =
                      line.user_id && !options.some((a) => a.out_user_id === line.user_id)
                        ? eligible.find((a) => a.out_user_id === line.user_id)
                        : undefined;
                    const dropdown = selected ? [selected, ...options] : options;
                    return (
                      <tr key={i} className="hover:bg-muted/30">
                        <td className="border px-2 py-1 text-center font-medium">{i + 1}</td>
                        <td className="border px-2 py-1">
                          {readOnly ? (
                            <span>{line.step_label || '—'}</span>
                          ) : (
                            <Select
                              value={line.step_label}
                              onValueChange={(v) => updateLine(i, 'step_label', v)}
                            >
                              <SelectTrigger className="h-7 text-xs border-0 shadow-none">
                                <SelectValue placeholder="구분 선택" />
                              </SelectTrigger>
                              <SelectContent>
                                {STEP_TEMPLATES.map((t) => (
                                  <SelectItem key={t.step_label} value={t.step_label}>
                                    {t.step_label}
                                  </SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          )}
                        </td>
                        <td className="border px-2 py-1">
                          <Badge variant="outline" className="text-[10px]">
                            {POSITION_LABELS[line.position] || line.position || '미지정'}
                          </Badge>
                        </td>
                        <td className="border px-2 py-1">
                          {readOnly ? (
                            <span>{line.user_name || '미지정'}</span>
                          ) : (
                            <Select
                              value={line.user_id || ''}
                              onValueChange={(v) => updateLine(i, 'user_id', v)}
                              disabled={!line.position}
                            >
                              <SelectTrigger className="h-7 text-xs border-0 shadow-none">
                                <SelectValue placeholder="결재자 선택">
                                  {line.user_name || '선택...'}
                                </SelectValue>
                              </SelectTrigger>
                              <SelectContent>
                                {!line.position && (
                                  <div className="px-3 py-2 text-xs text-muted-foreground">
                                    먼저 구분을 선택하세요.
                                  </div>
                                )}
                                {line.position && dropdown.length === 0 && (
                                  <div className="px-3 py-2 text-xs text-muted-foreground">
                                    {(line.position === 'owner_sm' || line.position === 'owner_cm')
                                      ? '발주처(client) 멤버·직책(OWNER_SM/CM)이 없습니다. 프로젝트 멤버를 확인하세요.'
                                      : '해당 단계에 맞는 결재자가 없습니다.'}
                                  </div>
                                )}
                                {dropdown.map((a) => (
                                  <SelectItem key={a.out_user_id} value={a.out_user_id}>
                                    {a.out_display_name}{' '}
                                    ({POSITION_LABELS[a.out_position] || a.out_position || a.out_role})
                                    {a.out_company_name && ` · ${a.out_company_name}`}
                                  </SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          )}
                        </td>
                        <td className="border px-2 py-1 text-muted-foreground">
                          {line.company_name || '—'}
                        </td>
                        {!readOnly && (
                          <td className="border px-2 py-1">
                            <div className="flex items-center justify-center gap-0.5">
                              <Button
                                size="icon"
                                variant="ghost"
                                className="h-6 w-6"
                                onClick={() => moveStep(i, -1)}
                                disabled={i === 0}
                              >
                                <ArrowUp className="h-3 w-3" />
                              </Button>
                              <Button
                                size="icon"
                                variant="ghost"
                                className="h-6 w-6"
                                onClick={() => moveStep(i, 1)}
                                disabled={i === lines.length - 1}
                              >
                                <ArrowDown className="h-3 w-3" />
                              </Button>
                              <Button
                                size="icon"
                                variant="ghost"
                                className="h-6 w-6 text-destructive"
                                onClick={() => removeStep(i)}
                              >
                                <Trash2 className="h-3 w-3" />
                              </Button>
                            </div>
                          </td>
                        )}
                      </tr>
                    );
                  })}
              </tbody>
            </table>
          </div>
        )}
      </CardContent>
    </Card>
  );
});

export default ApprovalLineManager;
export type { ApprovalLine };
