// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "\uD504\uB85C\uC81D\uD2B8 \uBAA9\uB85D",
  description: "\uD604\uC7AC \uB85C\uADF8\uC778\uD55C \uC0AC\uC6A9\uC790\uAC00 \uC811\uADFC \uAC00\uB2A5\uD55C \uC548\uC804\uAD00\uB9AC \uD504\uB85C\uC81D\uD2B8\uB97C \uC870\uD68C\uD569\uB2C8\uB2E4.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uC778\uC99D\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("projects").select("id,name,client_name,status,start_date,end_date").eq("is_deleted", false).order("created_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-work-permits.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_work_permits_default = defineTool2({
  name: "list_work_permits",
  title: "\uC791\uC5C5\uD5C8\uAC00\uC11C \uBAA9\uB85D",
  description: "\uD504\uB85C\uC81D\uD2B8\uC758 \uC791\uC5C5\uD5C8\uAC00\uC11C(\uC0C1\uD0DC/\uC720\uD615 \uD544\uD130 \uAC00\uB2A5)\uB97C \uCD5C\uB300 50\uAC74 \uC870\uD68C\uD569\uB2C8\uB2E4.",
  inputSchema: {
    project_id: z.string().uuid().describe("\uD504\uB85C\uC81D\uD2B8 UUID"),
    status: z.string().optional().describe("\uC2B9\uC778 \uC0C1\uD0DC \uD544\uD130 (\uC608: approved, pending)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uC778\uC99D\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("work_permits").select("id,title,permit_type,status,permit_date,valid_until,created_at").eq("project_id", project_id).eq("is_deleted", false).order("created_at", { ascending: false }).limit(50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { permits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-incidents.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_incidents_default = defineTool3({
  name: "list_incidents",
  title: "\uC0AC\uACE0 \uBCF4\uACE0\uC11C \uBAA9\uB85D",
  description: "\uD504\uB85C\uC81D\uD2B8\uC758 \uC0AC\uACE0(\uC7AC\uD574) \uBCF4\uACE0\uC11C\uB97C \uCD5C\uADFC 50\uAC74 \uC870\uD68C\uD569\uB2C8\uB2E4.",
  inputSchema: {
    project_id: z2.string().uuid().describe("\uD504\uB85C\uC81D\uD2B8 UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uC778\uC99D\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("incident_reports").select("id,incident_type,severity,occurred_at,description,status").eq("project_id", project_id).order("occurred_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { incidents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-risk-assessments.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_risk_assessments_default = defineTool4({
  name: "list_risk_assessments",
  title: "\uC704\uD5D8\uC131\uD3C9\uAC00 \uD68C\uCC28 \uBAA9\uB85D",
  description: "\uD504\uB85C\uC81D\uD2B8\uC758 \uC704\uD5D8\uC131\uD3C9\uAC00 \uD68C\uCC28\uB97C \uCD5C\uADFC 50\uAC74 \uC870\uD68C\uD569\uB2C8\uB2E4.",
  inputSchema: {
    project_id: z3.string().uuid().describe("\uD504\uB85C\uC81D\uD2B8 UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uC778\uC99D\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("assessment_runs").select("id,title,assessment_type,status,created_at").eq("project_id", project_id).eq("is_deleted", false).order("created_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assessments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iqtiozscqwuacgzrlfzu";
var mcp_default = defineMcp({
  name: "safenex-mcp",
  title: "SafeNex \uC548\uC804\uAD00\uB9AC MCP",
  version: "0.1.0",
  instructions: "\uB300\uD55C\uBBFC\uAD6D \uC0B0\uC5C5\uC548\uC804\uBCF4\uAC74\uBC95 \uAE30\uBC18 \uC548\uC804\uAD00\uB9AC\uC2DC\uC2A4\uD15C(SafeNex)\uC758 \uD504\uB85C\uC81D\uD2B8, \uC791\uC5C5\uD5C8\uAC00\uC11C, \uC704\uD5D8\uC131\uD3C9\uAC00, \uC0AC\uACE0\uBCF4\uACE0\uC11C\uB97C \uC870\uD68C\uD558\uB294 \uB3C4\uAD6C\uC785\uB2C8\uB2E4. \uBAA8\uB4E0 \uB3C4\uAD6C\uB294 \uB85C\uADF8\uC778\uD55C \uC0AC\uC6A9\uC790 \uAD8C\uD55C(RLS) \uC548\uC5D0\uC11C \uB3D9\uC791\uD569\uB2C8\uB2E4.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, list_work_permits_default, list_incidents_default, list_risk_assessments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
